// RSA-2048 ADB key persisted at ~/.tvlm/adbkey (PKCS#8 PEM) + ~/.tvlm/adbkey.pub (Google's adbkey.pub
// format). Tango's `AdbCredentialStore` contract: `generateKey()` once, `iterateKeys()` every time.
// `~/.android/adbkey` (Google adb's key) is offered as a second key, so a TV that already trusts the
// user's adb does not ask Allow again — and a wireless-debugging pairing done with `adb pair` works here.
import { createPrivateKey, createPublicKey, generateKeyPairSync, randomBytes, sign, type KeyObject } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { homedir, hostname, userInfo } from 'node:os';
import { dirname, join } from 'node:path';
import { adbGeneratePublicKey, type AdbCredentialStore, type AdbPrivateKey } from '@yume-chan/adb';

export const TVLM_DIR = join(homedir(), '.tvlm');
export const ADB_KEY_PATH = join(TVLM_DIR, 'adbkey');
export const GOOGLE_ADB_KEY_PATH = join(homedir(), '.android', 'adbkey');

function keyName(): string {
  let user = 'tvlm';
  try {
    user = userInfo().username || user;
  } catch {
    /* no user info (containers) */
  }
  return `${user}@${hostname()}`;
}

/** `adbkey.pub` line: base64(ADB public key struct) + space + name. */
export function publicKeyLine(privateKeyPkcs8: Uint8Array, name = keyName()): string {
  const pub = adbGeneratePublicKey(privateKeyPkcs8);
  return `${Buffer.from(pub).toString('base64')} ${name}\n`;
}

/** Accepts PKCS#8 ("PRIVATE KEY") and PKCS#1 ("RSA PRIVATE KEY", what Google adb writes). */
export function pemToPkcs8(pem: string): Uint8Array {
  const der = createPrivateKey(pem).export({ type: 'pkcs8', format: 'der' }) as Buffer;
  return new Uint8Array(der.buffer, der.byteOffset, der.byteLength);
}

async function loadKey(path: string, name: string): Promise<AdbPrivateKey | undefined> {
  try {
    const pem = await readFile(path, 'utf8');
    return { buffer: pemToPkcs8(pem), name };
  } catch {
    return undefined;
  }
}

export class NodeCredentialStore implements AdbCredentialStore {
  constructor(
    readonly path: string = ADB_KEY_PATH,
    /** Extra keys tried for signatures (never regenerated by us). */
    readonly extraPaths: readonly string[] = [GOOGLE_ADB_KEY_PATH],
  ) {}

  async generateKey(): Promise<AdbPrivateKey> {
    const { privateKey } = generateKeyPairSync('rsa', { modulusLength: 2048, publicExponent: 65537 });
    const pem = privateKey.export({ type: 'pkcs8', format: 'pem' }) as string;
    const buffer = pemToPkcs8(pem);
    await mkdir(dirname(this.path), { recursive: true });
    await writeFile(this.path, pem, { mode: 0o600 });
    await writeFile(`${this.path}.pub`, publicKeyLine(buffer));
    return { buffer, name: keyName() };
  }

  /** Our key first (that is the one the Allow dialog shows), then Google adb's if present. */
  async *iterateKeys(): AsyncGenerator<AdbPrivateKey, void, void> {
    const own = await loadKey(this.path, keyName());
    if (own) yield own;
    for (const p of this.extraPaths) {
      const k = await loadKey(p, keyName());
      if (k) yield k;
    }
  }

  /** Make sure a key exists (so the first connect does not have to generate one mid-handshake). */
  async ensure(): Promise<AdbPrivateKey> {
    for await (const k of this.iterateKeys()) return k;
    return this.generateKey();
  }

  /** PEM private keys + self-signed certs for TLS client auth, ours first. */
  async tlsIdentities(): Promise<Array<{ key: string; cert: string; path: string }>> {
    const out: Array<{ key: string; cert: string; path: string }> = [];
    for (const p of [this.path, ...this.extraPaths]) {
      try {
        const pem = await readFile(p, 'utf8');
        const key = createPrivateKey(pem);
        out.push({ key: key.export({ type: 'pkcs8', format: 'pem' }) as string, cert: selfSignedCertificate(key), path: p });
      } catch {
        /* absent */
      }
    }
    return out;
  }
}

// ---------------------------------------------------------------- X.509 for ADB-over-TLS
// adbd (Android 11+ wireless debugging) verifies the TLS client by the PUBLIC KEY inside the certificate,
// not by the certificate itself, so any self-signed cert over the paired/allowed key is accepted. Node has
// no X.509 *builder*, so here is the minimal DER: v3, CN=adb, sha256WithRSAEncryption, CA:TRUE (as adb's
// own x509_generator.cpp does), ten years.

function derLength(n: number): number[] {
  if (n < 0x80) return [n];
  const bytes: number[] = [];
  for (let v = n; v > 0; v >>= 8) bytes.unshift(v & 0xff);
  return [0x80 | bytes.length, ...bytes];
}

function concat(parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let o = 0;
  for (const p of parts) {
    out.set(p, o);
    o += p.length;
  }
  return out;
}

function tlv(tag: number, ...parts: Uint8Array[]): Uint8Array {
  const body = concat(parts);
  return concat([Uint8Array.from([tag, ...derLength(body.length)]), body]);
}

const SEQ = 0x30;
const SET = 0x31;

export function derOid(oid: string): Uint8Array {
  const parts = oid.split('.').map(Number);
  const bytes: number[] = [parts[0]! * 40 + parts[1]!];
  for (const p of parts.slice(2)) {
    const enc: number[] = [p & 0x7f];
    for (let v = p >> 7; v > 0; v >>= 7) enc.unshift(0x80 | (v & 0x7f));
    bytes.push(...enc);
  }
  return tlv(0x06, Uint8Array.from(bytes));
}

function derInteger(bytes: Uint8Array): Uint8Array {
  // Positive INTEGER: prefix 0x00 when the top bit is set.
  return tlv(0x02, bytes[0]! & 0x80 ? concat([Uint8Array.from([0]), bytes]) : bytes);
}

function derUtcTime(d: Date): Uint8Array {
  const s = d.toISOString().replace(/[-:T]/g, '').slice(2, 14) + 'Z'; // YYMMDDHHMMSSZ
  return tlv(0x17, Buffer.from(s, 'ascii'));
}

function derName(cn: string): Uint8Array {
  return tlv(SEQ, tlv(SET, tlv(SEQ, derOid('2.5.4.3'), tlv(0x0c, Buffer.from(cn, 'utf8')))));
}

const SHA256_RSA = tlv(SEQ, derOid('1.2.840.113549.1.1.11'), Uint8Array.from([0x05, 0x00]));

export function selfSignedCertificate(privateKey: KeyObject | string, opts: { cn?: string; years?: number; serial?: Uint8Array } = {}): string {
  const key = typeof privateKey === 'string' ? createPrivateKey(privateKey) : privateKey;
  const spki = createPublicKey(key).export({ type: 'spki', format: 'der' }) as Buffer;
  const now = new Date();
  const notBefore = new Date(now.getTime() - 86400_000);
  const notAfter = new Date(now.getTime() + (opts.years ?? 10) * 365 * 86400_000);
  const serial = opts.serial ?? randomBytes(16);
  const name = derName(opts.cn ?? 'adb');
  const basicConstraints = tlv(
    SEQ,
    derOid('2.5.29.19'),
    Uint8Array.from([0x01, 0x01, 0xff]), // critical
    tlv(0x04, tlv(SEQ, Uint8Array.from([0x01, 0x01, 0xff]))), // OCTET STRING { SEQUENCE { cA TRUE } }
  );
  const tbs = tlv(
    SEQ,
    tlv(0xa0, tlv(0x02, Uint8Array.from([2]))), // [0] version v3
    derInteger(serial),
    SHA256_RSA,
    name, // issuer
    tlv(SEQ, derUtcTime(notBefore), derUtcTime(notAfter)),
    name, // subject
    new Uint8Array(spki.buffer, spki.byteOffset, spki.byteLength),
    tlv(0xa3, tlv(SEQ, basicConstraints)), // [3] extensions
  );
  const signature = sign('sha256', tbs, key);
  const cert = tlv(SEQ, tbs, SHA256_RSA, tlv(0x03, Uint8Array.from([0]), new Uint8Array(signature.buffer, signature.byteOffset, signature.byteLength)));
  const b64 = Buffer.from(cert).toString('base64').replace(/(.{64})/g, '$1\n').trimEnd();
  return `-----BEGIN CERTIFICATE-----\n${b64}\n-----END CERTIFICATE-----\n`;
}
